### ISSUE TITLE
Сделать каркас приложения

### ISSUE THREAD

**Issue by NurGeo** [soul-workshop/front#5]
- [x] изучить архитектуру FSD
- [x] определить основные зоны приложения;
- [x] сделать для основных зон, компоненты;
- [x] сверстать все компоненты и убедиться что все работает;
- [x] убедиться что приложение адаптивно;

**Comment by Renatter** [comment]
https://github.com/soul-workshop/front/pull/9

**Comment by NurGeo** [comment]
Сделать:
- объект `AppState` с атрибутом "AppMode" с вариантами значения: "Browser" | "Mobile";
- Право на изменение его значения имеет AppComponent;
- Все компоненты логика которых зависит от "AppMode" должны "слушать" его значение и откликаться на его изменение;
